import Provider from "@/libs/Providers";
import "../globals.css";
import AuthNavbar from "@/Components/Header/AuthNavbar";
import { afacad, qwitcher_grypen, raleway } from "@/libs/fonts";
import { cn } from "@/libs/utils";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={cn(afacad, raleway, qwitcher_grypen, "antialiased")}
			>
				<AuthNavbar />
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
