import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/libs/utils";
import { afacad, raleway } from "@/libs/fonts";
import Provider from "@/libs/Providers";
import Navbar from "@/Components/Header/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(afacad, raleway, "antialiased")}>
				<Navbar />
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
